services:
  csharp:
    build:
      context: ..
      dockerfile: examples/csharp/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["csharp"]

  frontend:
    build:
      context: ..
      dockerfile: examples/frontend/Dockerfile
    ports:
      - "57661:57661"
    profiles: ["frontend"]

  fsharp:
    build:
      context: ..
      dockerfile: examples/fsharp/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["fsharp"]

  gleam:
    build:
      context: ..
      dockerfile: examples/gleam/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["gleam"]

  haskell:
    build:
      context: ..
      dockerfile: examples/haskell/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["haskell"]

  java:
    build:
      context: ..
      dockerfile: examples/java/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["java"]

  kotlin:
    build:
      context: ..
      dockerfile: examples/kotlin/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["kotlin"]

  ocaml:
    build:
      context: ..
      dockerfile: examples/ocaml/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["ocaml"]

  python:
    build:
      context: ..
      dockerfile: examples/python/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["python"]

  rust:
    build:
      context: ..
      dockerfile: examples/rust/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["rust"]

  scala:
    build:
      context: ..
      dockerfile: examples/scala/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["scala"]

  swift:
    build:
      context: ..
      dockerfile: examples/swift/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["swift"]

  typescript:
    build:
      context: ..
      dockerfile: examples/typescript/Dockerfile
    ports:
      - "57660:57660"
    profiles: ["typescript"]
